inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
