version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    working_directory: ~/yahtzee
    steps:
      - checkout
      - ruby/install-deps

  rspec:
    working_directory: ~/yahtzee
    docker:
      - image: cimg/ruby:3.2.2-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_ROOT_HOST: 127.0.0.1
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - ruby/install-deps
      - run:
        command: |
          mkdir -p /var/lib/apt/lists/partial
          chmod 644 /var/lib/apt/lists/*
      - run:
          command: apt-get update && apt-get install -y libvips42
          name: install libvips
      - run:
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
          name: Wait for DB
      - run:
          command: |
            mv config/database.yml.ci config/database.yml
            bundle exec rails db:create
            bundle exec rails db:schema:load --trace
          name: Database setup
      - run:
          command: |
            mv spec/support/capybara.rb.ci spec/support/capybara.rb
          name: capybara config
      - ruby/rspec-test:
          include: spec/**/*_spec.rb

  rubocop:
    working_directory: ~/yahtzee
    docker:
      - image: cimg/ruby:3.2.2
    resource_class: small
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rubocop-check:
          parallel: true

  heroku_deploy:
    working_directory: ~/yahtzee
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME

workflows:
  test_and_deploy:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - heroku_deploy:
          requires:
            - rspec
            - rubocop
